testsuite: use -v for easier locating failig command. Oracle now uses oracle13.tange.dk.

diff --git a/testsuite/wanted-results/parallel-local-3s b/testsuite/wanted-results/parallel-local-3s
--- a/testsuite/wanted-results/parallel-local-3s
+++ b/testsuite/wanted-results/parallel-local-3s
@@ -1,12 +1,19 @@
+echo '### bug #42089: --results with arg > 256 chars (should be 1 char shorter)'
 ### bug #42089: --results with arg > 256 chars (should be 1 char shorter)
+  parallel --results parallel_test_dir echo ::: 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456;   ls parallel_test_dir/1/
 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456
 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
+  rm -rf parallel_test_dir
+echo '**'
 **
+echo '### Test --halt-on-error 0';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 0;   echo $?;   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true";echo "sleep 4; non_exist") | parallel -j10 --halt 0;   echo $?
 ### Test --halt-on-error 0
 1
 2
 /bin/bash: non_exist: command not found
+echo '**'
 **
+echo '### Test --halt-on-error 1';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 1;   echo $?;   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true";echo "sleep 4; non_exist") | parallel -j10 --halt 1;   echo $?
 ### Test --halt-on-error 1
 1
 127
@@ -17,7 +24,9 @@ parallel: Starting no more jobs. Waiting for 3 jobs to finish. This job failed:
 sleep 2;false
 parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job failed:
 sleep 4; non_exist
+echo '**'
 **
+echo '### Test --halt-on-error 2';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 2;   echo $?;   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true";echo "sleep 4; non_exist") | parallel -j10 --halt 2;   echo $?
 ### Test --halt-on-error 2
 1
 1
@@ -25,7 +34,9 @@ parallel: This job failed:
 sleep 2;false
 parallel: This job failed:
 sleep 2;false
+echo '**'
 **
+echo '### Test last dying print --halt-on-error 1';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt 1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
 ### Test last dying print --halt-on-error 1
 exit code 9
 0
@@ -57,13 +68,16 @@ parallel: Starting no more jobs. Waiting for 2 jobs to finish. This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 8
 parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 9
+echo '### Test last dying print --halt-on-error 2';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt 2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
 ### Test last dying print --halt-on-error 2
 exit code 1
 0
 1
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 1
+echo '**'
 **
+echo '### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834';   seq 1 3 | parallel -j1 "sleep 2; echo {}" | parallel -kj2 echo
 ### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834
 1
 2
diff --git a/testsuite/wanted-results/parallel-local-ssh2 b/testsuite/wanted-results/parallel-local-ssh2
--- a/testsuite/wanted-results/parallel-local-ssh2
+++ b/testsuite/wanted-results/parallel-local-ssh2
@@ -1,14 +1,22 @@
+echo '### --filter-hosts --slf <()'
 ### --filter-hosts --slf <()
+  parallel --nonall --filter-hosts --slf <(echo localhost) echo OK
 OK
+echo '### --wd no-such-dir - csh'
 ### --wd no-such-dir - csh
+  stdout parallel --wd /no-such-dir -S csh@localhost echo ::: "ERROR IF PRINTED"; echo Exit code $?
 mkdir: cannot create directory ‘/no-such-dir’: Permission denied
 /no-such-dir: No such file or directory.
 Exit code 1
+echo '### --wd no-such-dir - tcsh'
 ### --wd no-such-dir - tcsh
+  stdout parallel --wd /no-such-dir -S tcsh@localhost echo ::: "ERROR IF PRINTED"; echo Exit code $?
 mkdir: cannot create directory ‘/no-such-dir’: Permission denied
 /no-such-dir: No such file or directory.
 Exit code 1
+echo '### --wd no-such-dir - bash'
 ### --wd no-such-dir - bash
+  stdout parallel --wd /no-such-dir -S parallel@localhost echo ::: "ERROR IF PRINTED"; echo Exit code $?
 mkdir: cannot create directory ‘/no-such-dir’: Permission denied
 bash: line 0: cd: /no-such-dir: No such file or directory
 Exit code 1
diff --git a/testsuite/wanted-results/parallel-local114 b/testsuite/wanted-results/parallel-local114
--- a/testsuite/wanted-results/parallel-local114
+++ b/testsuite/wanted-results/parallel-local114
@@ -1,14 +1,23 @@
+echo "### --line-buffer"
 ### --line-buffer
+  seq 10 | parallel -j20 --line-buffer  'seq {} 10 | pv -qL 10' > /tmp/parallel_l$$;   seq 10 | parallel -j20                'seq {} 10 | pv -qL 10' > /tmp/parallel_$$;   cat /tmp/parallel_l$$ | wc;   diff /tmp/parallel_$$ /tmp/parallel_l$$ >/dev/null ; echo These must diff: $?
      55      55     120
 These must diff: 1
+echo "### --pipe --line-buffer"
 ### --pipe --line-buffer
+  seq 200| parallel -N10 -L1 --pipe  -j20 --line-buffer --tagstring {#} pv -qL 10 > /tmp/parallel_pl$$;   seq 200| parallel -N10 -L1 --pipe  -j20               --tagstring {#} pv -qL 10 > /tmp/parallel_p$$;   cat /tmp/parallel_pl$$ | wc;   diff /tmp/parallel_p$$ /tmp/parallel_pl$$ >/dev/null ; echo These must diff: $?
     200     400    1202
 These must diff: 1
+echo "### --pipe --line-buffer --compress"
 ### --pipe --line-buffer --compress
+  seq 200| parallel -N10 -L1 --pipe  -j20 --line-buffer --compress --tagstring {#} pv -qL 10 | wc
     200     400    1202
+echo "### bug #41482: --pipe --compress blocks at different -j/seq combinations"
 ### bug #41482: --pipe --compress blocks at different -j/seq combinations
+  seq 1 | parallel -k -j2 --compress -N1 -L1 --pipe cat;   echo echo 1-4 + 1-4
 1
 echo 1-4 + 1-4
+    seq 4 | parallel -k -j3 --compress -N1 -L1 -vv echo;   echo 4 times wc to stderr to stdout
 echo 1
 1
 echo 2
@@ -18,37 +27,52 @@ echo 3
 echo 4
 4
 4 times wc to stderr to stdout
+    (seq 4 | parallel -k -j3 --compress -N1 -L1 --pipe wc '>&2') 2>&1 >/dev/null
       1       1       2
       1       1       2
       1       1       2
       1       1       2
+  echo 1 2 3 4
 1 2 3 4
+    seq 4 | parallel -k -j3 --compress echo;   echo 1 2 3 4
 1
 2
 3
 4
 1 2 3 4
+    seq 4 | parallel -k -j1 --compress echo;   echo 1 2
 1
 2
 3
 4
 1 2
+    seq 2 | parallel -k -j1 --compress echo;   echo 1 2 3
 1
 2
 1 2 3
+    seq 3 | parallel -k -j2 --compress -N1 -L1 --pipe cat; echo "### bug #41609: --compress fails"
 1
 2
 3
 ### bug #41609: --compress fails
+  seq 12 | parallel --compress --compress-program bzip2 -k seq {} 1000000 | md5sum
 24812dd0f24a26d08a780f988b9d5ad2  -
+  seq 12 | parallel --compress -k seq {} 1000000 | md5sum
 24812dd0f24a26d08a780f988b9d5ad2  -
+echo "### --compress race condition (use nice): Fewer than 400 would run"
 ### --compress race condition (use nice): Fewer than 400 would run
+  seq 400| nice parallel -j200 --compress echo | wc
     400     400    1492
+echo "### -v --pipe: Dont spawn too many - 1 is enough"
 ### -v --pipe: Dont spawn too many - 1 is enough
+  seq 1 | parallel -j10 -v --pipe cat
 cat
 1
+echo "### Test -N0 and --tagstring (fails)"
 ### Test -N0 and --tagstring (fails)
+  echo tagstring arg | parallel --tag -N0 echo foo
 	foo
+echo "### Test -I";   seq 1 10 | parallel -k 'seq 1 {} | parallel -k -I :: echo {} ::'
 ### Test -I
 1 1
 2 1
@@ -105,6 +129,7 @@ cat
 10 8
 10 9
 10 10
+echo "### Test -X -I";   seq 1 10 | parallel -k 'seq 1 {} | parallel -j1 -X -k -I :: echo a{} b::'
 ### Test -X -I
 a1 b1
 a2 b1 b2
@@ -116,6 +141,7 @@ a7 b1 b2 b3 b4 b5 b6 b7
 a8 b1 b2 b3 b4 b5 b6 b7 b8
 a9 b1 b2 b3 b4 b5 b6 b7 b8 b9
 a10 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10
+echo "### Test -m -I";   seq 1 10 | parallel -k 'seq 1 {} | parallel -j1 -m -k -I :: echo a{} b::'
 ### Test -m -I
 a1 b1
 a2 b1 2
@@ -127,18 +153,23 @@ a7 b1 2 3 4 5 6 7
 a8 b1 2 3 4 5 6 7 8
 a9 b1 2 3 4 5 6 7 8 9
 a10 b1 2 3 4 5 6 7 8 9 10
+echo "### Test max line length -m -I";   seq 1 60000 | parallel -I :: -m -j1 echo a::b::c |   tee >(sort |md5sum) >/tmp/114-a$$;   export CHAR=$(cat /tmp/114-a$$ | wc -c);   export LINES=$(cat /tmp/114-a$$ | wc -l);   echo "Chars per line ($CHAR/$LINES): "$(echo "$CHAR/$LINES" | bc);   rm /tmp/114-a$$
 ### Test max line length -m -I
 31d9274be5fdc2de59487cb05ba57776  -
 Chars per line (697800/6): 116300
+echo "### Test max line length -X -I";   seq 1 60000 | parallel -I :: -X -j1 echo a::b::c |   tee >(sort |md5sum) >/tmp/114-b$$;   export CHAR=$(cat /tmp/114-b$$ | wc -c);   export LINES=$(cat /tmp/114-b$$ | wc -l);   echo "Chars per line ($CHAR/$LINES): "$(echo "$CHAR/$LINES" | bc);   rm /tmp/114-b$$
 ### Test max line length -X -I
 22074f9acada52462defb18ba912d744  -
 Chars per line (817788/7): 116826
+echo "### bug #36659: --sshlogin strips leading slash from ssh command";   parallel --sshlogin '/usr/bin/ssh localhost' echo ::: OK
 ### bug #36659: --sshlogin strips leading slash from ssh command
 OK
+echo "### bug #36660: --workdir mkdir does not use --sshlogin custom ssh";   rm -rf /tmp/foo36660;   cd /tmp; echo OK > parallel_test.txt;   ssh () { echo Failed; };   export -f ssh;   parallel --workdir /tmp/foo36660/bar --transfer --sshlogin '/usr/bin/ssh localhost' cat ::: parallel_test.txt; echo "bug #36657: --load does not work with custom ssh";   cd /tmp; echo OK > parallel_test.txt;   ssh () { echo Failed; };   export -f ssh;   parallel --load=1000% -S "/usr/bin/ssh localhost" echo ::: OK
 ### bug #36660: --workdir mkdir does not use --sshlogin custom ssh
 OK
 bug #36657: --load does not work with custom ssh
 OK
+echo "bug #34958: --pipe with record size measured in lines";   seq 10 | parallel -k --pipe -L 4 cat\;echo bug 34958-1
 bug #34958: --pipe with record size measured in lines
 1
 2
@@ -152,6 +183,7 @@ bug 34958-1
 9
 10
 bug 34958-1
+echo "bug #37325: Inefficiency of --pipe -L";   seq 2000 | parallel -k --pipe --block 1k -L 4 wc\;echo FOO | uniq
 bug #37325: Inefficiency of --pipe -L
     276     276     996
 FOO
@@ -171,6 +203,7 @@ FOO
 FOO
     180     180     900
 FOO
+echo "bug #34958: --pipe with record size measured in lines";   seq 10 | parallel -k --pipe -l 4 cat\;echo bug 34958-2
 bug #34958: --pipe with record size measured in lines
 1
 2
@@ -184,6 +217,7 @@ bug 34958-2
 9
 10
 bug 34958-2
+echo "### Test --results";   mkdir -p /tmp/parallel_results_test;   parallel -k --results /tmp/parallel_results_test/testA echo {1} {2} ::: I II ::: III IIII;   ls /tmp/parallel_results_test/testA/*/*/*/*/*; rm -rf /tmp/parallel_results_test/testA*
 ### Test --results
 I III
 I IIII
@@ -197,6 +231,7 @@ II IIII
 /tmp/parallel_results_test/testA/1/II/2/III/stdout
 /tmp/parallel_results_test/testA/1/II/2/IIII/stderr
 /tmp/parallel_results_test/testA/1/II/2/IIII/stdout
+echo "### Test --res";   mkdir -p /tmp/parallel_results_test;   parallel -k --res /tmp/parallel_results_test/testD echo {1} {2} ::: I II ::: III IIII;   ls /tmp/parallel_results_test/testD/*/*/*/*/*; rm -rf /tmp/parallel_results_test/testD*
 ### Test --res
 I III
 I IIII
@@ -210,6 +245,7 @@ II IIII
 /tmp/parallel_results_test/testD/1/II/2/III/stdout
 /tmp/parallel_results_test/testD/1/II/2/IIII/stderr
 /tmp/parallel_results_test/testD/1/II/2/IIII/stdout
+echo "### Test --result";   mkdir -p /tmp/parallel_results_test;   parallel -k --result /tmp/parallel_results_test/testE echo {1} {2} ::: I II ::: III IIII;   ls /tmp/parallel_results_test/testE/*/*/*/*/*; rm -rf /tmp/parallel_results_test/testE*
 ### Test --result
 I III
 I IIII
@@ -223,6 +259,7 @@ II IIII
 /tmp/parallel_results_test/testE/1/II/2/III/stdout
 /tmp/parallel_results_test/testE/1/II/2/IIII/stderr
 /tmp/parallel_results_test/testE/1/II/2/IIII/stdout
+echo "### Test --results --header :";   mkdir -p /tmp/parallel_results_test;   parallel -k --header : --results /tmp/parallel_results_test/testB echo {1} {2} ::: a I II ::: b III IIII;   ls /tmp/parallel_results_test/testB/*/*/*/*/*; rm -rf /tmp/parallel_results_test/testB*
 ### Test --results --header :
 I III
 I IIII
@@ -236,6 +273,7 @@ II IIII
 /tmp/parallel_results_test/testB/a/II/b/III/stdout
 /tmp/parallel_results_test/testB/a/II/b/IIII/stderr
 /tmp/parallel_results_test/testB/a/II/b/IIII/stdout
+echo "### Test --results --header : named - a/b swapped";   mkdir -p /tmp/parallel_results_test;   parallel -k --header : --results /tmp/parallel_results_test/testC echo {a} {b} ::: b III IIII ::: a I II;   ls /tmp/parallel_results_test/testC/*/*/*/*/*; rm -rf /tmp/parallel_results_test/testC*
 ### Test --results --header : named - a/b swapped
 I III
 II III
@@ -249,11 +287,13 @@ II IIII
 /tmp/parallel_results_test/testC/a/II/b/III/stdout
 /tmp/parallel_results_test/testC/a/II/b/IIII/stderr
 /tmp/parallel_results_test/testC/a/II/b/IIII/stdout
+echo "### Test --results --header : piped";   mkdir -p /tmp/parallel_results_test;   (echo Col; perl -e 'print "backslash\\tab\tslash/null\0eof\n"') | parallel  --header : --result /tmp/parallel_results_test/testF true;   find /tmp/parallel_results_test/testF/*/*/* | sort; rm -rf /tmp/parallel_results_test/testF*
 ### Test --results --header : piped
 /tmp/parallel_results_test/testF/Col/backslash\\tab/2
 /tmp/parallel_results_test/testF/Col/backslash\\tab/2/slash\_null\0eof
 /tmp/parallel_results_test/testF/Col/backslash\\tab/2/slash\_null\0eof/stderr
 /tmp/parallel_results_test/testF/Col/backslash\\tab/2/slash\_null\0eof/stdout
+echo "### Test --results --header : piped - non-existing column header";   mkdir -p /tmp/parallel_results_test;   (printf "Col1\t\n"; printf "v1\tv2\tv3\n"; perl -e 'print "backslash\\tab\tslash/null\0eof\n"') | parallel --header : --result /tmp/parallel_results_test/testG true; find /tmp/parallel_results_test/testG/ | sort; rm -rf /tmp/parallel_results_test/testG*
 ### Test --results --header : piped - non-existing column header
 /tmp/parallel_results_test/testG/
 /tmp/parallel_results_test/testG/Col1
diff --git a/testsuite/wanted-results/parallel-local9 b/testsuite/wanted-results/parallel-local9
--- a/testsuite/wanted-results/parallel-local9
+++ b/testsuite/wanted-results/parallel-local9
@@ -1,27 +1,60 @@
+echo 'bug #41613: --compress --line-buffer no newline';
 bug #41613: --compress --line-buffer no newline
+  perl -e 'print "It worked"'| parallel --pipe --compress --line-buffer cat; echo
 It worked
+echo 'bug #41613: --compress --line-buffer no --tagstring';
 bug #41613: --compress --line-buffer no --tagstring
+  diff     <(nice perl -e 'for("x011".."x110"){print "$_\t", ("\n", map { rand } (1..100000)) }'|       parallel -N10 -L1 --pipe -j6 --block 20M --compress       pv -qL 1000000 | perl -pe 's/(....).*/$1/')     <(nice perl -e 'for("x011".."x110"){print "$_\t", ("\n", map { rand } (1..100000)) }'|       parallel -N10 -L1 --pipe -j6 --block 20M --compress --line-buffer       pv -qL 1000000 | perl -pe 's/(....).*/$1/')     >/dev/null   || (echo 'Good: --line-buffer matters'; false) && echo 'Bad: --line-buffer not working'
 Good: --line-buffer matters
+echo 'bug #41613: --compress --line-buffer with --tagstring';
 bug #41613: --compress --line-buffer with --tagstring
+  diff     <(nice perl -e 'for("x011".."x110"){print "$_\t", ("\n", map { rand } (1..100000)) }'|       parallel -N10 -L1 --pipe -j6 --block 20M --compress --tagstring {#}       pv -qL 1000000 | perl -pe 's/(....).*/$1/')     <(nice perl -e 'for("x011".."x110"){print "$_\t", ("\n", map { rand } (1..100000)) }'|       parallel -N10 -L1 --pipe -j6 --block 20M --compress --tagstring {#} --line-buffer       pv -qL 1000000 | perl -pe 's/(....).*/$1/')     >/dev/null   || (echo 'Good: --line-buffer matters'; false) && echo 'Bad: --line-buffer not working'
 Good: --line-buffer matters
+echo 'bug #41613: --compress --line-buffer - no newline';
 bug #41613: --compress --line-buffer - no newline
+ echo 'pipe compress tagstring'
 pipe compress tagstring
-1	OK
+ perl -e 'print "O"'| parallel --compress --tagstring {#} --pipe --line-buffer cat
+1	O echo "K"
+K
+ echo 'pipe compress notagstring'
 pipe compress notagstring
-OK
+ perl -e 'print "O"'| parallel --compress --pipe --line-buffer cat
+O echo "K"
+K
+ echo 'pipe nocompress tagstring'
 pipe nocompress tagstring
-1	OK
+ perl -e 'print "O"'| parallel --tagstring {#} --pipe --line-buffer cat
+1	O echo "K"
+K
+ echo 'pipe nocompress notagstring'
 pipe nocompress notagstring
-OK
+ perl -e 'print "O"'| parallel --pipe --line-buffer cat
+O echo "K"
+K
+ echo 'nopipe compress tagstring'
 nopipe compress tagstring
-1	OK
+ parallel --compress --tagstring {#} --line-buffer echo {} O ::: -n
+1	O echo "K"
+K
+ echo 'nopipe compress notagstring'
 nopipe compress notagstring
-OK
+ parallel --compress --line-buffer echo {} O ::: -n
+O echo "K"
+K
+ echo 'nopipe nocompress tagstring'
 nopipe nocompress tagstring
-1	OK
+ parallel --tagstring {#} --line-buffer echo {} O ::: -n
+1	O echo "K"
+K
+ echo 'nopipe nocompress notagstring'
 nopipe nocompress notagstring
-OK
+ parallel --line-buffer echo {} O ::: -n
+O echo "K"
+K
+echo 'bug #41412: --timeout + --delay causes deadlock';
 bug #41412: --timeout + --delay causes deadlock
+  seq 10 | parallel -j10 --timeout 1 --delay .3 echo;
 1
 2
 3
@@ -32,17 +65,21 @@ bug #41412: --timeout + --delay causes deadlock
 8
 9
 10
+  parallel -j3 --timeout 1 --delay 2 echo ::: 1 2 3;
 1
 2
 3
+  parallel -j10 --timeout 2.2 --delay 3 "sleep {}; echo {}" ::: 1 2 4 5 6
 1
 2
+echo '### Test --spreadstdin - more procs than args';   rm -f /tmp/parallel.ss.*;   seq 1 5 | stdout parallel -j 10 --spreadstdin 'cat >/tmp/parallel.ss.$PARALLEL_SEQ' >/dev/null;   cat /tmp/parallel.ss.*;
 ### Test --spreadstdin - more procs than args
 1
 2
 3
 4
 5
+echo '### Test --spreadstdin - more args than procs';   rm -f /tmp/parallel.ss2.*;   seq 1 10 | stdout parallel -j 5 --spreadstdin 'cat >/tmp/parallel.ss2.$PARALLEL_SEQ' >/dev/null;   cat /tmp/parallel.ss2.*
 ### Test --spreadstdin - more args than procs
 1
 2
@@ -54,53 +91,101 @@ bug #41412: --timeout + --delay causes deadlock
 8
 9
 10
+nice nice seq 1 1000 | nice nice parallel -j1 --spreadstdin cat "|cat "|wc -c
 3893
+nice nice seq 1 10000 | nice nice parallel -j10 --spreadstdin cat "|cat "|wc -c
 48894
+nice nice seq 1 100000 | nice nice parallel -j1 --spreadstdin cat "|cat "|wc -c
 588895
+nice nice seq 1 1000000 | nice nice parallel -j10 --spreadstdin cat "|cat "|wc -c
 6888896
+seq 1 10 | parallel --recend "\n" -j1 --spreadstdin gzip -9 >/tmp/foo.gz
+echo '### Test --spreadstdin - similar to the failing below';   nice seq 1 100000 | nice nice parallel --recend "\n" -j10 --spreadstdin gzip -9 >/tmp/foo2.gz;   diff <(nice seq 1 100000) <(zcat /tmp/foo2.gz |sort -n);   diff <(nice seq 1 100000|wc -c) <(zcat /tmp/foo2.gz |wc -c)
 ### Test --spreadstdin - similar to the failing below
+echo '### Test --spreadstdin - this failed during devel';   nice seq 1 1000000 | md5sum;   nice seq 1 1000000 | nice nice parallel --recend "\n" -j10 --spreadstdin gzip -9 | zcat | sort -n | md5sum
 ### Test --spreadstdin - this failed during devel
 8a7095c1c23bfadc311fe6b16d950582  -
 8a7095c1c23bfadc311fe6b16d950582  -
+echo '### Test --spreadstdin -k';   nice seq 1 1000000 | nice nice parallel -k --recend "\n" -j10 --spreadstdin gzip -9 | zcat | md5sum
 ### Test --spreadstdin -k
 8a7095c1c23bfadc311fe6b16d950582  -
+echo '### Test --spreadstdin --files';   nice seq 1 1000000 | shuf | parallel --files --recend "\n" -j10 --spreadstdin sort -n | parallel -Xj1 sort -nm {} ";"rm {} | md5sum
 ### Test --spreadstdin --files
 8a7095c1c23bfadc311fe6b16d950582  -
+echo '### Test --number-of-cpus';   stdout parallel --number-of-cpus
 ### Test --number-of-cpus
 1
+echo '### Test --number-of-cores';   stdout parallel --number-of-cores
 ### Test --number-of-cores
 8
+echo '### Test --use-cpus-instead-of-cores';   (seq 1 4 | stdout parallel --use-cpus-instead-of-cores -j100% sleep) && echo CPUs done &   (seq 1 4 | stdout parallel -j100% sleep) && echo cores done &   echo 'Cores should complete first on machines with less than 4 physical CPUs';   wait
 ### Test --use-cpus-instead-of-cores
 Cores should complete first on machines with less than 4 physical CPUs
 cores done
 CPUs done
+echo '### Test --tag ::: a ::: b';   stdout parallel -k --tag -j1  echo stderr-{.} ">&2;" echo stdout-{} ::: a ::: b
 ### Test --tag ::: a ::: b
 a b	stdout-a b
 a b	stderr-a b
+echo '### Test --tag ::: a b';   stdout parallel -k --tag -j1  echo stderr-{.} ">&2;" echo stdout-{} ::: a b
 ### Test --tag ::: a b
 a	stdout-a
 a	stderr-a
 b	stdout-b
 b	stderr-b
+echo '### Test --tag -X ::: a b';   stdout parallel -k --tag -X -j1  echo stderr-{.} ">&2;" echo stdout-{} ::: a b
 ### Test --tag -X ::: a b
 a b	stdout-a stdout-b
 a b	stderr-a stderr-b
+echo '### Test bash redirection <()';
 ### Test bash redirection <()
+  parallel 'cat <(echo {}); echo b' ::: a
 a
 b
+echo '### Test bug https://savannah.gnu.org/bugs/index.php?33352'
 ### Test bug https://savannah.gnu.org/bugs/index.php?33352
+# produce input slowly to parallel so that it will reap a process
+# while blocking in read()
+# Having found the solution it is suddenly very easy to reproduce the
+# problem - even on other hardware:
+#
+# perl -e '@x=1 .. 17000; for(1..30) { print "@x\n"}' | pv -qL 200000
+# |parallel -j2 --pipe --keeporder --block 150000 cat | md5sum
+#
+# This gives different md5sums for each run.
+#
+# The problem is that read(STDIN) is being interrupted by a dead
+# child. The chance of this happening is very small if there are few
+# children dying or read(STDIN) never has to wait for data.
+#
+# The test above forces data to arrive slowly (using pv) which causes
+# read(STDIN) to take a long time - thus being interrupted by a dead
+# child.
+echo "# md5sum - directly"
 # md5sum - directly
+  perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo "# parallel | md5sum"
 # parallel | md5sum
+  nice nice perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | pv -qL 1000000 |     $PAR cat | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo "# --recend ''"
 # --recend ''
+  nice nice perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | pv -qL 1000000 |     $PAR --recend '' cat | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo "# --recend '' --files"
 # --recend '' --files
+  nice nice perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | pv -qL 1000000 |     $PAR --recend '' --files cat | parallel -Xj1 cat {} ';' rm {} | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo "# --recend '' --files --tmpdir"
 # --recend '' --files --tmpdir
+  nice nice perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | pv -qL 1000000 |     $PAR --recend '' --files --tmpdir /dev/shm cat | parallel -Xj1 cat {} ';' rm {} | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo "# --recend '' --files --halt-on-error"
 # --recend '' --files --halt-on-error
+  nice nice perl -e '@x=1 .. 17000; for(1..100) { print "@x\n"}' | pv -qL 1000000 |     $PAR --recend '' --files --halt-on-error 2 cat | parallel -Xj1 cat {} ';' rm {} | md5sum
 350eda13a37912d755c9d733d149bdaf  -
+echo '### Test of -j filename - non-existent file';   nice stdout parallel -j no_such_file echo ::: 1
 ### Test of -j filename - non-existent file
 Usage:
 parallel [options] [command [arguments]] < list_of_arguments
@@ -131,14 +216,18 @@ When using programs that use GNU Parallel to process data for publication please
 O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
 ;login: The USENIX Magazine, February 2011:42-47.
 parallel: Error: Parsing of --jobs/-j/--max-procs/-P failed.
+echo '### Test of -j filename';   echo 3 >/tmp/jobs_to_run1;   parallel -j /tmp/jobs_to_run1 -v sleep {} ::: 10 8 6 5 4;   # Should give 6 8 10 5 4
 ### Test of -j filename
 sleep 6
 sleep 8
 sleep 10
 sleep 5
 sleep 4
+echo '### Test ::::'
 ### Test ::::
+echo '### Change --arg-file-sep'
 ### Change --arg-file-sep
+$XAP --arg-file-sep :::: -k echo {1} {2} :::: <(seq 1 10) <(seq 5 15)
 1 5
 2 6
 3 7
@@ -150,6 +239,7 @@ sleep 4
 9 13
 10 14
 1 15
+$XAP --arg-file-sep .--- -k echo {1} {2} .--- <(seq 1 10) <(seq 5 15)
 1 5
 2 6
 3 7
@@ -161,6 +251,7 @@ sleep 4
 9 13
 10 14
 1 15
+$XAP --argfilesep :::: -k echo {1} {2} :::: <(seq 1 10) <(seq 5 15)
 1 5
 2 6
 3 7
@@ -172,6 +263,7 @@ sleep 4
 9 13
 10 14
 1 15
+$XAP --argfilesep .--- -k echo {1} {2} .--- <(seq 1 10) <(seq 5 15)
 1 5
 2 6
 3 7
@@ -183,20 +275,30 @@ sleep 4
 9 13
 10 14
 1 15
+echo '### Test xapply --max-replace-args'
 ### Test xapply --max-replace-args
+seq 0 7 | $XAP -k --max-replace-args=3 echo {3} {2} {1}
 2 1 0
 5 4 3
 7 6
+echo '### Test -N'
 ### Test -N
+seq 1 5 | $XAP -kN3 echo {1} {2} {3}
 1 2 3
 4 5
+echo '### Test -N with 0'
 ### Test -N with 0
+seq 0 7 | $XAP -kN3 echo {1} {2} {3}
 0 1 2
 3 4 5
 6 7
+echo '### Test :::: on nonexistent'
 ### Test :::: on nonexistent
+stdout $XAP -k echo {1} {2} {3} :::: nonexistent
 parallel: Error: Cannot open input file `nonexistent': No such file or directory.
+echo '### Test :::: two files'
 ### Test :::: two files
+$XAP -k echo {1} {2} :::: <(seq 1 10) <(seq 5 15)
 1 5
 2 6
 3 7
@@ -208,81 +310,116 @@ parallel: Error: Cannot open input file `nonexistent': No such file or directory
 9 13
 10 14
 1 15
+echo '### Test -d, ::::'
 ### Test -d, ::::
+$XAP -kd, 'echo a{1} {2}b' :::: <(echo 1,2,3,) <(echo 5,6,7,8)
 a1 5b
 a2 6b
 a3 7b
 a
  8
 b
+echo '### Test -d, :::: one file too much'
 ### Test -d, :::: one file too much
+$XAP -kd, echo 'a{1}' '{2}b' :::: <(echo 1,2,3,) <(echo 5,6,7,8) <(echo 9,0)
 a1 5b
 a2 6b
 a3 7b
 a
  8
 b
+echo '### Bug: did not quote'
 ### Bug: did not quote
+$XAP echo {1} {2} :::: <(echo '>') <(echo b)
 > b
+echo '### Quote test triplet 1'
 ### Quote test triplet 1
+$XAP -kv :::: <(echo 'echo a'; echo 'echo b')
 echo a
 a
 echo b
 b
+$XAP -kv -a <(echo 'echo a'; echo 'echo b')
 echo a
 a
 echo b
 b
+(echo 'echo a'; echo 'echo b') | $XAP -kv
 echo a
 a
 echo b
 b
+echo '### Quote test triplet 2'
 ### Quote test triplet 2
+$XAP -kv echo :::: <(echo 'echo a'; echo 'echo b')
 echo echo\ a
 echo a
 echo echo\ b
 echo b
+$XAP -kv -a <(echo 'echo a'; echo 'echo b') echo
 echo echo\ a
 echo a
 echo echo\ b
 echo b
+(echo 'echo a'; echo 'echo b') | $XAP -kv echo
 echo echo\ a
 echo a
 echo echo\ b
 echo b
+echo '### Quoting if there is a command and 2 arg files'
 ### Quoting if there is a command and 2 arg files
+$XAP -kv echo :::: <(echo 'echo a') <(echo 'echo b')
 echo echo\ a echo\ b
 echo a echo b
+echo '### Quoting if there is a command and 2 arg files of uneven length'
 ### Quoting if there is a command and 2 arg files of uneven length
+$XAP -kv echo :::: <(echo 'echo a';echo a1) <(echo 'echo b')
 echo echo\ a echo\ b
 echo a echo b
 echo a1 echo\ b
 a1 echo b
+echo '### Quoting if there is no command and 2 arg files'
 ### Quoting if there is no command and 2 arg files
+$XAP -kv :::: <(echo 'echo a') <(echo 'echo b')
 echo a echo b
 a echo b
+echo '### Quoting if there is no command and 2 arg files of uneven length'
 ### Quoting if there is no command and 2 arg files of uneven length
+$XAP -kv :::: <(echo 'echo a';echo echo a1) <(echo 'echo b')
 echo a echo b
 a echo b
 echo a1 echo b
 a1 echo b
+echo '### Test multiple -a'
 ### Test multiple -a
+$XAP -kv -a <(echo a) -a <(echo b) echo {2} {1}
 echo b a
 b a
+$XAP -kv echo {2} {1} :::: <(echo a) <(echo b)
 echo b a
 b a
+echo '### Multiple -a: An unused file'
 ### Multiple -a: An unused file
+$XAP -kv -a <(echo a) -a <(echo b) -a <(echo c) echo {2} {1}
 echo b a
 b a
+$XAP -kv echo {2} {1} :::: <(echo a) <(echo b) <(echo c)
 echo b a
 b a
+echo '### Multiple -a: nonexistent'
 ### Multiple -a: nonexistent
+stdout $XAP -kv echo {2} {1} :::: nonexist nonexist2
 parallel: Error: Cannot open input file `nonexist': No such file or directory.
+stdout $XAP -kv -a nonexist -a nonexist2 echo {2} {1}
 parallel: Error: Cannot open input file `nonexist': No such file or directory.
+echo '### Test {#.}'
 ### Test {#.}
+$XAP -kv -a <(echo a-noext) -a <(echo b-withext.extension) -a <(echo c-ext.gif) echo {3.} {2.} {1.}
 echo c-ext b-withext a-noext
 c-ext b-withext a-noext
+echo "### Tests that failed for OO-rewrite"
 ### Tests that failed for OO-rewrite
+parallel -u --semaphore seq 1 10 '|' pv -qL 20; sem --wait; echo done
 1
 2
 3
@@ -294,25 +431,38 @@ c-ext b-withext a-noext
 9
 10
 done
+echo a | parallel echo {1}
 a
+echo "echo a" | parallel
 a
+parallel -j1 -I :: -X echo 'a::b::^c::[.}c' ::: 1
 a1b1^c1[.}c
+echo "### BUG: The length for -X is not close to max (131072)"
 ### BUG: The length for -X is not close to max (131072)
+seq 1 4000 | parallel -k -X echo {.} aa {}{.} {}{}d{} {}dd{}d{.} |head -n 1 |wc
       1   12821  131060
+echo "### BUG: empty lines with --show-limit"
 ### BUG: empty lines with --show-limit
+echo | parallel  --show-limits
 Maximal size of command: 131071
 Maximal used size of command: 131071
 
 Execution of  will continue now, and it will try to read its input
 and run commands; if this is not what you wanted to happen, please
 press CTRL-D or CTRL-C
+echo '### Test -N'
 ### Test -N
+seq 1 5 | parallel -kN3 echo {1} {2} {3}
 1 2 3
 4 5
+echo '### Test --arg-file-sep with files of different lengths'
 ### Test --arg-file-sep with files of different lengths
+parallel --xapply --arg-file-sep :::: -k echo {1} {2} :::: <(seq 1 1) <(seq 3 4)
 1 3
 1 4
+echo '### Test respect -s'
 ### Test respect -s
+parallel -kvm -IARG -s15 echo ARG ::: 1 22 333 4444 55555 666666 7777777 88888888 999999999
 echo 1 22 333
 1 22 333
 echo 4444
@@ -327,31 +477,53 @@ echo 88888888
 88888888
 echo 999999999
 999999999
+echo '### Test eof string after :::'
 ### Test eof string after :::
+parallel -k -E ole echo ::: foo ole bar
 foo
+echo '### Test -C and --trim rl'
 ### Test -C and --trim rl
+parallel -k -C %+ echo '"{1}_{3}_{2}_{4}"' ::: 'a% c %%b' 'a%c% b %d'
 a_b_c_
 a_b_c_d
+echo '### Test empty input'
 ### Test empty input
+</dev/null parallel -j +0 echo
+echo '### Test -m'
 ### Test -m
+seq 1 2 | parallel -k -m echo
 1
 2
+echo '### Test :::'
 ### Test :::
+parallel echo ::: 1
 1
+echo '### Test context_replace'
 ### Test context_replace
+echo a | parallel -qX echo  "'"{}"' "
 'a' 
+echo '### Test -N2 {2}'
 ### Test -N2 {2}
+seq 1 4 | parallel -kN2 echo arg1:{1} seq:'$'PARALLEL_SEQ arg2:{2}
 arg1:1 seq:1 arg2:2
 arg1:3 seq:2 arg2:4
+echo '### Test -E (should only output foo ole)'
 ### Test -E (should only output foo ole)
+(echo foo; echo '';echo 'ole ';echo bar;echo quux) | parallel -kr -L2 -E bar echo
 foo ole 
+parallel -kr -L2 -E bar echo ::: foo '' 'ole ' bar quux
 foo ole 
+echo '### Test -r (should only output foo ole bar\nquux)'
 ### Test -r (should only output foo ole bar\nquux)
+parallel -kr -L2 echo ::: foo '' 'ole ' bar quux
 foo ole bar
 quux
+echo '### Test of tab as colsep'
 ### Test of tab as colsep
+printf 'def\tabc\njkl\tghi' | parallel -k --colsep '\t' echo {2} {1}
 abc def
 ghi jkl
+parallel -k -a <(printf 'def\tabc\njkl\tghi') --colsep '\t' echo {2} {1}
 abc def
 ghi jkl
 ### Test of -j filename with file content changing (missing -k is correct)
diff --git a/testsuite/wanted-results/test15 b/testsuite/wanted-results/test15
--- a/testsuite/wanted-results/test15
+++ b/testsuite/wanted-results/test15
@@ -29,120 +29,170 @@ sleep 0.1; echo opt--interactive 3 ?...y
 opt--interactive 1
 opt--interactive 3
 
+echo '### Test killing children with --timeout and exit value (failed if timed out)'
 ### Test killing children with --timeout and exit value (failed if timed out)
+  pstree | grep sleep | grep -v anacron | grep -v screensave | wc;   parallel --timeout 3 'true {} ; for i in `seq 100 120`; do bash -c "(sleep $i)" & sleep $i & done; wait; echo No good' ::: 1000000000 1000000001 ;   echo $?; sleep 7; pstree | grep sleep | grep -v anacron | grep -v screensave | wc
       0       0       0
 2
       0       0       0
+echo '### Test -L -l and --max-lines'
 ### Test -L -l and --max-lines
+(echo a_b;echo c) | parallel -km -L2 echo
 a_b
 c
+(echo a_b;echo c) | parallel -k -L2 echo
 a_b c
+(echo a_b;echo c) | xargs -L2 echo
 a_b c
+echo '### xargs -L1 echo'
 ### xargs -L1 echo
+(echo a_b;echo c) | parallel -km -L1 echo
 a_b
 c
+(echo a_b;echo c) | parallel -k -L1 echo
 a_b
 c
+(echo a_b;echo c) | xargs -L1 echo
 a_b
 c
+echo 'Lines ending in space should continue on next line'
 Lines ending in space should continue on next line
+echo '### xargs -L1 echo'
 ### xargs -L1 echo
+(echo a_b' ';echo c;echo d) | parallel -km -L1 echo
 a_b c
 d
+(echo a_b' ';echo c;echo d) | parallel -k -L1 echo
 a_b c
 d
+(echo a_b' ';echo c;echo d) | xargs -L1 echo
 a_b c
 d
+echo '### xargs -L2 echo'
 ### xargs -L2 echo
+(echo a_b' ';echo c;echo d;echo e) | parallel -km -L2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel -k -L2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs -L2 echo
 a_b c d
 e
+echo '### xargs -l echo'
 ### xargs -l echo
+(echo a_b' ';echo c;echo d;echo e) | parallel -l -km echo # This behaves wrong
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel -l -k echo # This behaves wrong
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs -l echo
 a_b c
 d
 e
+echo '### xargs -l2 echo'
 ### xargs -l2 echo
+(echo a_b' ';echo c;echo d;echo e) | parallel -km -l2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel -k -l2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs -l2 echo
 a_b c d
 e
+echo '### xargs -l1 echo'
 ### xargs -l1 echo
+(echo a_b' ';echo c;echo d;echo e) | parallel -km -l1 echo
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel -k -l1 echo
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs -l1 echo
 a_b c
 d
 e
+echo '### xargs --max-lines=2 echo'
 ### xargs --max-lines=2 echo
+(echo a_b' ';echo c;echo d;echo e) | parallel -km --max-lines 2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel -k --max-lines 2 echo
 a_b c d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs --max-lines=2 echo
 a_b c d
 e
+echo '### xargs --max-lines echo'
 ### xargs --max-lines echo
+(echo a_b' ';echo c;echo d;echo e) | parallel --max-lines -km echo # This behaves wrong
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | parallel --max-lines -k echo # This behaves wrong
 a_b c
 d
 e
+(echo a_b' ';echo c;echo d;echo e) | xargs --max-lines echo
 a_b c
 d
 e
+echo '### test too long args'
 ### test too long args
+perl -e 'print "z"x1000000' | parallel echo 2>&1
 parallel: Error: Command line too long (1000005 >= 131071) at number 0: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...
+perl -e 'print "z"x1000000' | xargs echo 2>&1
 xargs: argument line too long
+(seq 1 10; perl -e 'print "z"x1000000'; seq 12 15) | stdout parallel -j1 -km -s 10 echo
 1 2
 3 4
 5 6
 7 8
 9 10
 parallel: Error: Command line too long (1000007 >= 10) at number 0: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...
+(seq 1 10; perl -e 'print "z"x1000000'; seq 12 15) | stdout xargs -s 10 echo
 1 2
 3 4
 5 6
 7 8
 xargs: argument line too long
 9 10
+(seq 1 10; perl -e 'print "z"x1000000'; seq 12 15) | stdout parallel -j1 -kX -s 10 echo
 1 2
 3 4
 5 6
 7 8
 9 10
 parallel: Error: Command line too long (1000007 >= 10) at number 0: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...
+echo '### Test -x'
 ### Test -x
+(seq 1 10; echo 12345; seq 12 15) | stdout parallel -j1 -km -s 10 -x echo
 1 2
 3 4
 5 6
 7 8
 9 10
 parallel: Error: Command line too long (10 >= 10) at number 0: 12345...
+(seq 1 10; echo 12345; seq 12 15) | stdout parallel -j1 -kX -s 10 -x echo
 1 2
 3 4
 5 6
 7 8
 9 10
 parallel: Error: Command line too long (10 >= 10) at number 0: 12345...
+(seq 1 10; echo 12345; seq 12 15) | stdout xargs -s 10 -x echo
 1 2
 3 4
 5 6
 xargs: argument line too long
 7 8
+(seq 1 10; echo 1234; seq 12 15) | stdout parallel -j1 -km -s 10 -x echo
 1 2
 3 4
 5 6
@@ -153,6 +203,7 @@ xargs: argument line too long
 13
 14
 15
+(seq 1 10; echo 1234; seq 12 15) | stdout parallel -j1 -kX -s 10 -x echo
 1 2
 3 4
 5 6
@@ -163,6 +214,7 @@ xargs: argument line too long
 13
 14
 15
+(seq 1 10; echo 1234; seq 12 15) | stdout xargs -s 10 -x echo
 1 2
 3 4
 5 6
@@ -173,7 +225,9 @@ xargs: argument line too long
 13
 14
 15
+echo '### Test -a and --arg-file: Read input from file instead of stdin'
 ### Test -a and --arg-file: Read input from file instead of stdin
+seq 1 10 >/tmp/$$-1; parallel -k -a /tmp/$$-1 echo
 1
 2
 3
@@ -184,6 +238,7 @@ xargs: argument line too long
 8
 9
 10
+seq 1 10 >/tmp/$$-2; parallel -k --arg-file /tmp/$$-2 echo
 1
 2
 3
