parallel: Implemented --halt -1 and --halt -2.

diff --git a/testsuite/wanted-results/parallel-local-3s b/testsuite/wanted-results/parallel-local-3s
--- a/testsuite/wanted-results/parallel-local-3s
+++ b/testsuite/wanted-results/parallel-local-3s
@@ -36,9 +36,31 @@ parallel: This job failed:
 sleep 2;false
 echo '**'
 **
+echo '### Test --halt -1';   (echo "sleep 1;false"; echo "sleep 2;true";echo "sleep 3;false") | parallel -j10 --halt-on-error -1;   echo $?;   (echo "sleep 1;false"; echo "sleep 2;true";echo "sleep 3;false";echo "sleep 4; non_exist") | parallel -j10 --halt -1;   echo $?
+### Test --halt -1
+0
+0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish. This job succeeded:
+sleep 2;true
+parallel: Starting no more jobs. Waiting for 3 jobs to finish. This job succeeded:
+sleep 2;true
+/bin/bash: non_exist: command not found
+echo '**'
+**
+echo '### Test --halt -2';   (echo "sleep 1;false"; echo "sleep 2;true";echo "sleep 3;false") | parallel -j10 --halt-on-error -2;   echo $?;   (echo "sleep 1;false"; echo "sleep 2;true";echo "sleep 3;false";echo "sleep 4; non_exist") | parallel -j10 --halt -2;   echo $?
+### Test --halt -2
+0
+0
+parallel: This job succeeded:
+sleep 2;true
+parallel: This job succeeded:
+sleep 2;true
+echo '**'
+**
 echo '### Test last dying print --halt-on-error 1';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt 1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
 ### Test last dying print --halt-on-error 1
 exit code 9
+0
 0
 1
 parallel: Starting no more jobs. Waiting for 9 jobs to finish. This job failed:
@@ -62,7 +84,6 @@ perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 6
 parallel: Starting no more jobs. Waiting for 3 jobs to finish. This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 7
 8
-0
 parallel: Starting no more jobs. Waiting for 2 jobs to finish. This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 8
 9
@@ -72,9 +93,50 @@ echo '### Test last dying print --halt-on-error 2';   (seq 0 8;echo 0; echo 9) |
 ### Test last dying print --halt-on-error 2
 exit code 1
 0
+0
 1
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 1
+echo '### Test last dying print --halt-on-error -1';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt -1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
+### Test last dying print --halt-on-error -1
+exit code 0
+0
+0
+1
+parallel: Starting no more jobs. Waiting for 9 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
+2
+parallel: Starting no more jobs. Waiting for 8 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 2
+3
+parallel: Starting no more jobs. Waiting for 7 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 3
+4
+parallel: Starting no more jobs. Waiting for 6 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 4
+5
+parallel: Starting no more jobs. Waiting for 5 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 5
+6
+parallel: Starting no more jobs. Waiting for 4 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 6
+7
+parallel: Starting no more jobs. Waiting for 3 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 7
+8
+parallel: Starting no more jobs. Waiting for 2 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 8
+9
+parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 9
+echo '### Test last dying print --halt-on-error -2';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt -2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
+### Test last dying print --halt-on-error -2
+exit code 0
+0
+0
+1
+parallel: This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
 echo '**'
 **
 echo '### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834';   seq 1 3 | parallel -j1 "sleep 2; echo {}" | parallel -kj2 echo
