Fixed bug #44553: --rpl should replace the longest expression first.

diff --git a/testsuite/wanted-results/parallel-local-mem b/testsuite/wanted-results/parallel-local-mem
--- a/testsuite/wanted-results/parallel-local-mem
+++ b/testsuite/wanted-results/parallel-local-mem
@@ -1,19 +1,24 @@
+make[2]: Entering directory `/home/tange/privat/parallel/testsuite'
+VBoxManage controlvm CentOS3-root:centos3 savestate
+VBoxManage controlvm RedHat9-root:redhat9 savestate
+VBoxManage controlvm OracleXE savestate
+make[2]: Leaving directory `/home/tange/privat/parallel/testsuite'
 echo '### Trouble reading a record > 2 GB for certain versions of Perl (substr($a,0,2G+1)="fails")'
 ### Trouble reading a record > 2 GB for certain versions of Perl (substr($a,0,2G+1)="fails")
 echo '### perl -e $buf=("x"x(2**31))."x"; substr($buf,0,2**31+1)=""; print length $buf'
 ### perl -e $buf=("x"x(2**31))."x"; substr($buf,0,2**31+1)=""; print length $buf
-'
-/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
-/bin/bash: -c: line 1: syntax error: unexpected end of file
-echo 'Eats 2.5 GB'
+echo 'Eats 4 GB'
+Eats 4 GB
+perl -e '$buf=("x"x(2**31))."x"; substr($buf,0,2**31+1)=""; print length $buf."\n"'
+1echo 'Eats 2.5 GB'
 Eats 2.5 GB
-  (yes "`echo {1..100}`" | head -c 2300M; echo ged) |   PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl `which parallel` -k --block 2G --pipe --recend ged md5sum
-131cbd7a7f1d19de3dabb379c716396b  -
+  (yes "`seq 3000`" | head -c 2300M; echo ged) |   PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl `which parallel` -k --block 2G --pipe --recend ged md5sum
+7be046296f6b0cde6049a11c116908ea  -
 68b329da9893e34099c7d8ad5cb9c940  -
 parallel: Warning: --blocksize >= 2G causes problems. Using 2G-1
 echo 'Eats 2.5 GB'
 Eats 2.5 GB
-  (yes "`echo {1..100}`" | head -c 2300M; echo ged) |   PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl `which parallel` -k --block 2G --pipe --recend ged cat | wc -c
+  (yes "`seq 3000`" | head -c 2300M; echo ged) |   PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl `which parallel` -k --block 2G --pipe --recend ged cat | wc -c
 2411724804
 parallel: Warning: --blocksize >= 2G causes problems. Using 2G-1
 echo '**'
@@ -22,7 +27,7 @@ echo '### bug #44358: 2 GB records cause problems for -N'
 ### bug #44358: 2 GB records cause problems for -N
 echo '5 GB version: Eats 12.5 GB'
 5 GB version: Eats 12.5 GB
-  (yes "`echo {1..100}`" | head -c 5000000000; echo FOO;    yes "`echo {1..100}`" | head -c 3000000000; echo FOO;    yes "`echo {1..100}`" | head -c 1000000000;) |    PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl    `which parallel` --pipe --recend FOO -N2 --block 1g -k LANG=c wc -c
+  (yes "`seq 3000`" | head -c 5000000000; echo FOO;    yes "`seq 3000`" | head -c 3000000000; echo FOO;    yes "`seq 3000`" | head -c 1000000000;) |    PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl    `which parallel` --pipe --recend FOO -N2 --block 1g -k LANG=c wc -c
 8000000007
 1000000001
 parallel: Warning: A record was longer than 1000000000. Increasing to --blocksize 1300000001
@@ -30,7 +35,7 @@ parallel: Warning: A record was longer than 1300000001. Increasing to --blocksiz
 parallel: Warning: A record was longer than 1690000003. Increasing to --blocksize 2147483647
 echo '2 GB version: eats 10 GB'
 2 GB version: eats 10 GB
-  (yes "`echo {1..100}`" | head -c 2300M; echo FOO;    yes "`echo {1..100}`" | head -c 2300M; echo FOO;    yes "`echo {1..100}`" | head -c 1000M;) |    PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl    `which parallel` --pipe --recend FOO -N2 --block 1g -k LANG=c wc -c
+  (yes "`seq 3000`" | head -c 2300M; echo FOO;    yes "`seq 3000`" | head -c 2300M; echo FOO;    yes "`seq 3000`" | head -c 1000M;) |    PERL5LIB=input-files/perl-v5.14.2/lib input-files/perl-v5.14.2/perl    `which parallel` --pipe --recend FOO -N2 --block 1g -k LANG=c wc -c
 4823449607
 1048576001
 parallel: Warning: A record was longer than 1000000000. Increasing to --blocksize 1300000001
@@ -44,3 +49,14 @@ echo '### -L >4GB'
 parallel: Warning: A record was longer than 1000000000. Increasing to --blocksize 1300000001
 parallel: Warning: A record was longer than 1300000001. Increasing to --blocksize 1690000003
 parallel: Warning: A record was longer than 1690000003. Increasing to --blocksize 2147483647
+make[2]: Entering directory `/home/tange/privat/parallel/testsuite'
+# Make sure we can reach the virtual machines
+sudo ifconfig wlan0:0 192.168.1.72
+# If they are already running: Don't fail
+VBoxManage startvm CentOS3-root:centos3 || VBoxManage controlvm CentOS3-root:centos3 resume || true
+Waiting for VM "CentOS3-root:centos3" to power on...
+VM "CentOS3-root:centos3" has been successfully started.
+VBoxManage startvm RedHat9-root:redhat9 || VBoxManage controlvm RedHat9-root:redhat9 resume || true
+Waiting for VM "RedHat9-root:redhat9" to power on...
+VM "RedHat9-root:redhat9" has been successfully started.
+make[2]: Leaving directory `/home/tange/privat/parallel/testsuite'
